# write a program to input eight numbers from the user and display all the unique numbers (once)

s = set()
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)
n=input("Enter the number: ")
s.add(n)

print(s)